hostname bgpd-R6
password en
enable password en

router bgp 6
  no bgp ebgp-requires-policy
  no bgp network import-check
  bgp router-id 6.6.6.6
  
  network 11.0.1.0/24
  network 11.0.2.0/24

  neighbor 9.0.8.1 remote-as 5
  neighbor 9.0.8.1 timers 5 5

log file /tmp/R6-bgpd-hard.log
log stdout